### PR TITLE
Pre-fill some configs and fix ssh command

### PR DESCRIPTION
**Pull request by joetech**
- [x] Pre-fill some of the configuration values to reduce copy/paste needs
 - [x] Update README to make more sense with the pre-fills
 - [x] Fix the example ssh command

### CODE REVIEW

**Comment by joetech** [comment]
What's the expectation for PR reviews?  I think this could be useful to add in.

**Comment by joetech** [comment]
@ajotwani Is this being reviewed or does it need changes?  I'm not sure of the status on this.

**Comment by hakanoodle** [comment]
Definitely something we are reviewing. Should be merging this shortly, along with some more improvements.

**Comment by ajotwani** [comment]
@joetech yes, this is being reviewed. We'll be sure to include this in the next update.

**Comment by joetech** [comment]
Thanks, @ajotwani

**Pull request merged**
